### ISSUE TITLE
How to integrate my entity vector into model ?

### ISSUE THREAD

**Issue by BettyHcZhang** [dalab/end2end_neural_el#11]
Hi , I want to integrate my entity embeddings to your model. Is the **nnid** in **end2end_neural_el/data/entities/entities_universe.txt** is the right order of the embedding organized?
In the other words, how to organize the embeddings' order ? **according to nnid ascending** ? so that  **ent_vecs.npy**  can work smothly with the upper layyers?
Call for your help,thank you  very much!

**Comment by BettyHcZhang** [comment]
In my view , the right order of embedding is the line number of the file  **wikiid2nnid/wikiid2nnid.txt**. That is the wikiid in the first line of  **wikiid2nnid/wikiid2nnid.txt** , then the first line of  **ent_vecs.npy** is the embedding according to this wikiid .

**Comment by NikosKolitsas** [comment]
So the neural network uses the entity embeddings that are returned from the funtion code.model.util.load_ent_vecs. This is the embeddings array. And also uses the mapping returned from code.preprocessing.util.load_wikiid2nnid  so those two should match (the embeddings array and the mapping) in order to work properly.
So if you use your own entities created in whichever way just make sure for the above. If you use this code for preprocessing etc this is already handled. Specifically:
The lua code found [here](https://github.com/dalab/deep-ed) at the 13 step runs the relatedness.lua script which is slightly modified to read the entities_universe.txt and create entity vectors for the entities found there. It adds some more entities, reorders them and then creates those two files nnid to wikiid mappings under the folder end2end_neural_el/data/entities/wikiid2nnid

**Comment by lbozarth** [comment]
Hi, to clarify. If I include an additional 3M entity vectors generated from the most recent 2020 wikidump. The model can detect "Ilhan Omar" from the sentence "Ilhan Omar is an American politician serving as the U.S. Representative for Minnesota's 5th congressional district since 2019." even though there is no labeled training data for her.
