### ISSUE TITLE
how to training my private entity vector?

### ISSUE THREAD

**Issue by loveJasmine** [dalab/end2end_neural_el#3]
any details, I see the the Gerbil evaluation part

**Comment by NikosKolitsas** [comment]
The following documentation provides detailed instructions:
https://github.com/dalab/end2end_neural_el/blob/master/create_entity_vectors.md
Furthermore, since the entity vectors were part of another paper and they were just used here it would be useful to check the corresponding paper https://github.com/octavian-ganea/deep-ed
