### ISSUE TITLE
An inconsistency in the README

### ISSUE THREAD

**Issue by se4u** [dalab/end2end_neural_el#6]
I am trying to understand the README especially the part about pre-processing for training entity vectors. The README mentions first that `We have pretrained 502661 entity vectors.` 
and then it says  `... we have created entity vectors for 366255 entities from many different popular datasets.` 

Also, 
1. the `entities/entities_universe.txt` file contains `470,105` entities
2. the `basic_data/persons.txt` contains `1,119,040` persons
3. the `basic_data/wiki_name_id_map.txt` contains `4,399,390` lines
4. the `entities/extension_entities/ent_vecs/ent_vecs.npy` file has `18,613` embeddings.
5. the `tfrecords/paper_models/embeddings_array.npy` file has `48,643` embeddings.

All of these numbers are different from `502,661` or `366,255`.

1.  Could you clarify which file stores the pretrained entity embeddings? 
2. I want to use the same pre-processed data that you used to create the pre-trained entity vectors. I.e. I want to use the same vocabulary files, comprehensive list of entities, same description data and linked data. And then I want to retrain the entity vectors. My understanding is that I need to follow [the creating-entity-vectors section](https://github.com/dalab/end2end_neural_el#creating-entity-vectors) in the README. But it's a little confusing. What is the purpose of Gerbil in that section? I thought Gerbil is used only during evaluation not during preprocessing. Are we creating  *_RLTD files from deep-ed for each new dataset?

3. In the original deep-ed code the `generated` folder contains the following files
```
 520M ent_name_id_map.t7  ← ← ←
 8.4G wiki_canonical_words.txt   ← ← ←
  88G wiki_hyperlink_contexts.csv    ← ← ←

 9.5M all_candidate_ents_ed_rltd_datasets_RLTD.t7 
  13M common_top_words_freq_vectors_w2v.t7 
 775M crosswikis_wikipedia_p_e_m.txt
 5.0M empty_page_ents.txt
  22M ent_name_id_map_RLTD.t7
 4.0K ent_vecs
  95M ent_wiki_freq.txt
 563M GoogleNews-vectors-negative300.t7
 7.3M relatedness_test.t7
 8.9M relatedness_validate.t7
 4.0K test_train_data
 1.5G wiki_canonical_words_RLTD.txt   
  48G wiki_hyperlink_contexts_RLTD.csv
 329M wikipedia_p_e_m.txt
  11M word_wiki_freq.txt
 749M yago_p_e_m.txt
```
The top three files are sufficient for generating the entity vectors. How are these 3 files generated in the neew end-to-end neural entity linking code base?

**Comment by Jorigorn** [comment]
> 

> 2\. What is the purpose of Gerbil in that section? I thought Gerbil is used only during evaluation not during preprocessing.
see end2end_neural_el/code/gerbil/server.py:
        if args.build_entity_universe:
            buildEntityUniverse.process(*read_json(post_data))
            response = []

It used for get the data sent by by Gerbil, but return empty rather than return a model prediction  . aka, there is some public available entity linking data-set in Gerbil. We can get that data-sets as out training data.  

> 2\. Are we creating  *_RLTD files from deep-ed for each new dataset?
with *_RLTD  means this is restricted dataset only contain the entity showed up the Aida-CoNll, and the other datasets got from  Gerbil. because the whole wikipedia contains more that 4M entities 

see deep-ed/entities/learn_e2v/learn_a.lua
cmd:option('-entities', 'RLTD',
  'Set of entities for which we train embeddings: 4EX (tiny, for debug) | ' .. 
  'RLTD (restricted set) | ALL (all Wiki entities, too big to fit on a single GPU)')

Please correct me if I understand it wrong.
I am training the whole wiki plus my own  entity vector.

I spited the  **ent_id_map** **wiki_canonical_words** **wiki_hyperlink_contexts** into 4 different parts and train them separately. But don't know why I got super low relatedness score . less than 0.1


zchen@ccp ~/experiments/end2end_neural_el/deep-ed/data/generated2
 % ll
total 96G
drwxrwxr-x 2 zchen zchen 4,0K Dez 30 23:46 .
drwxr-xr-x 8 zchen zchen 4,0K Dez 30 22:05 ..
-rw-rw-r-- 1 zchen zchen  27M Dez 30 23:28 ent_id_map_1.txt.v2
-rw-rw-r-- 1 zchen zchen  29M Dez 30 23:34 ent_id_map_2.txt.v2
-rw-rw-r-- 1 zchen zchen  30M Dez 30 23:40 ent_id_map_3.txt.v2
-rw-rw-r-- 1 zchen zchen  30M Dez 30 23:46 ent_id_map_4.txt.v2
-rw-rw-r-- 1 zchen zchen 3,9G Dez 30 23:28 wiki_canonical_words_1.txt.v2
-rw-rw-r-- 1 zchen zchen 1,8G Dez 30 23:34 wiki_canonical_words_2.txt.v2
-rw-rw-r-- 1 zchen zchen 1,5G Dez 30 23:40 wiki_canonical_words_3.txt.v2
-rw-rw-r-- 1 zchen zchen 1,4G Dez 30 23:46 wiki_canonical_words_4.txt.v2
-rw-rw-r-- 1 zchen zchen  41G Dez 30 23:34 wiki_hyperlink_contexts_1.txt.v2
-rw-rw-r-- 1 zchen zchen  19G Dez 30 23:40 wiki_hyperlink_contexts_2.txt.v2
-rw-rw-r-- 1 zchen zchen  15G Dez 30 23:46 wiki_hyperlink_contexts_3.txt.v2
-rw-rw-r-- 1 zchen zchen  13G Dez 30 23:52 wiki_hyperlink_contexts_4.txt.v2

Thanks

**Comment by NikosKolitsas** [comment]
I updated the readme file. Please check [here](https://github.com/dalab/end2end_neural_el/blob/master/create_entity_vectors.md).

**Comment by NikosKolitsas** [comment]
> Also,
> 
> 1. the `entities/entities_universe.txt` file contains `470,105` entities
> 2. the `basic_data/persons.txt` contains `1,119,040` persons
> 3. the `basic_data/wiki_name_id_map.txt` contains `4,399,390` lines
> 4. the `entities/extension_entities/ent_vecs/ent_vecs.npy` file has `18,613` embeddings.
> 5. the `tfrecords/paper_models/embeddings_array.npy` file has `48,643` embeddings.

These are implementation details and code that was written in order to perform some data transformation, and evaluation on the specific datasets and platform so I never took the time to clean it.

1. As it is mentioned in the updated instructions the entities_universe.txt contains all the entities needed for the datasets AIDA, ACE2004, AQUAINT, MSNBC, CLUEWEB
2. This file is not related to entity vectors and has almost no usage. It is only used for the coreference heuristic mentioned in the paper (a small heuristic that added a small improvement).
3. This file is a map between wikipedia article names and ids. This contains all the wikipedia articles so more than 4 millions.
4. Everything that has name "extension" is something that you can forget about it. The reason for using them that I trained the 484048 entities and then after a couple of months I decided to evaluate it on more datasets (on Gerbil) so I needed extra entity vectors (the extension_entities) which I obviously trained at a later stage and separately. 
5. These are the word embeddings (word2vec). This is built from the preprocessing/prepro_util.py code function build_word_char_maps. Our word vocabulary consists of every word that appears in the aforementioned datasets.

**Comment by NikosKolitsas** [comment]
> * Could you clarify which file stores the pretrained entity embeddings?
data/entities/ent_vecs/ent_vecs.npy
and 
data/entities/extension_entities/ent_vecs/ent_vecs.npy

> * I want to use the same pre-processed data that you used to create the pre-trained entity vectors. I.e. I want to use the same vocabulary files, comprehensive list of entities, same description data and linked data. And then I want to retrain the entity vectors. My understanding is that I need to follow [the creating-entity-vectors section](https://github.com/dalab/end2end_neural_el#creating-entity-vectors) in the README. But it's a little confusing. What is the purpose of Gerbil in that section? I thought Gerbil is used only during evaluation not during preprocessing. Are we creating  *_RLTD files from deep-ed for each new dataset?
Please look again the updated instructions. You are right it is confusing but this code is just a wrapper code to connect this project with a previous one that was in Lua and Torch.
So in essence just edit the entities_universe.txt file put all the wikiids for which you want entity vectors there and then follow the instructions from [this](https://github.com/dalab/deep-ed) project.

The Gerbil in that stage is just used in order to access-read the different datasets. Unfortunately, every dataset in entity linking is written in different format. So for the datasets AIDA, ACE2004, AQUAINT, MSNBC, CLUEWEB I have written code that takes the different formats and converts them to a simplified and uniform one but for the rest of the datasets I "accessed" them through Gerbil (receiving post requests) and reading the content.
