### ISSUE TITLE
question about some file

### ISSUE THREAD

**Issue by stanpcf** [dalab/end2end_neural_el#7]
thanks for your great work.
I have some question about some questions.
![image](https://user-images.githubusercontent.com/13925796/50831609-5d195f00-1386-11e9-8162-19b9a236065f.png)
the picture is the `data` dir. I can't find how to generate the `nnid2wikiid.txt` and `wikiid2nnid.txt`

**Comment by NikosKolitsas** [comment]
As it is described in [this section](https://github.com/dalab/end2end_neural_el/blob/master/create_entity_vectors.md#commands-to-be-executed-for-recreating-all-the-entities-used-for-the-paper-experiments) in order to create the entity vectors you have to execute the commands found [here](https://github.com/dalab/deep-ed). The command number 13 executes also the script deep-ed/deep-ed-master/entities/relatedness/relatedness.lua  which reads the file end2end_neural_el/data/entities/entities_universe.txt adds some more entities (needed for the training) and then creates the files nnid2wikiid.txt and wikiid2nnid.txt
