### ISSUE TITLE
KB may need to update

### ISSUE THREAD

**Issue by Nelsonvon** [dalab/end2end_neural_el#9]
I'm testing this software with my own corpus, but the knowledge base seems doesn't contain entities which came out in recent years. Mentions such as ISIS, Eric Snowden, or "president" (which represents Obama) don't have a correct candidate entity or even don't exist in the KB.
How can I update the pre-trained candidate entities and the corresponding embeddings by myself?
Thx

**Comment by NikosKolitsas** [comment]
Yes, this is true. It is also mentioned in the paper that we use a Wikipedia dump of 2014. In order to create your own entity vectors please follow the instructions found in the two following links:
https://github.com/dalab/end2end_neural_el/blob/master/create_entity_vectors.md
https://github.com/dalab/deep-ed
